#!/usr/bin/env bash
# Claude Code PreToolUse hook — block edits to harness/lint/build configs and
# ADRs. Rule-tampering is the article's named cheat path: when the agent hits
# a lint or schema error, the cheapest move is to delete the rule. This hook
# makes that move impossible from within Claude.
#
# Protected:
#   - biome.json, .oxlintrc*, tsconfig*.json
#   - lefthook.yml
#   - pnpm-lock.yaml, pnpm-workspace.yaml
#   - .github/workflows/*.yml (CI is the L3 guardrail; agents must not edit it)
#   - docs/adr/*.md           (ADRs are immutable once accepted; ADR-0007)
#   - .claude/settings.json   (the harness config that defines this hook)
#   - .claude/hooks/*         (the hook scripts themselves)
#
# Exit codes follow the Claude Code spec: 2 blocks the tool call and surfaces
# stderr to the agent; 0 allows it.
#
# Humans editing these files do so from a non-Claude session. The bias is
# "always block in agent flow" — there is no reliable way to detect a human
# from inside a hook, so we don't try (issue #43).

set -euo pipefail

input="$(cat)"
file="$(jq -r '.tool_input.file_path // .tool_input.path // empty' <<<"$input")"

[ -z "$file" ] && exit 0

# Normalize to a path relative to the project root if possible, so the
# matchers below work whether the agent passes an absolute or repo-relative
# path.
ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
rel="${file#"$ROOT"/}"
base="${rel##*/}"

block() {
  local reason="$1"
  cat >&2 <<EOF
kata harness — edit to protected config blocked
[$rel]
WHY: $reason. ADR-0007 (self-applied harness) says rule-tampering is the
agent's cheapest cheat path; the hook closes it.
FIX: do not edit the config to silence a check. Fix the underlying code. If
the rule itself is wrong, open a PR from a non-Claude shell.
EOF
  exit 2
}

# Lint / format / build configs at the repo root.
case "$base" in
  biome.json)            block "biome.json is the formatter/lint config" ;;
  .oxlintrc*)            block "Oxlint config is the linter ruleset" ;;
  tsconfig*.json)        block "TypeScript config defines the typecheck surface" ;;
  lefthook.yml|lefthook-local.yml)
                         block "Lefthook config defines the pre-commit guardrail" ;;
  pnpm-lock.yaml)        block "pnpm-lock.yaml is regenerated by pnpm install, not hand-edited" ;;
  pnpm-workspace.yaml)   block "pnpm workspace manifest is a build-graph config" ;;
esac

# Path-based matches (file basename isn't enough).
case "$rel" in
  .github/workflows/*.yml|.github/workflows/*.yaml)
    block "GitHub Actions workflows are the L3 CI guardrail" ;;
  docs/adr/*.md)
    # _template.md is the scaffold used to create new ADRs — humans copy it,
    # they don't edit it from an agent session either.
    block "ADRs are immutable once accepted (ADR-0007). New ADRs are added from a non-Claude shell" ;;
  .claude/settings.json)
    block ".claude/settings.json is the harness config that wires this hook" ;;
  .claude/hooks/*)
    block "hook scripts define the guardrails — edits would let the agent rewrite its own rules" ;;
esac

exit 0
