// Templates for the runnable example app that `kata init --with-example` writes
// (ADR-0015 / issue #101). Four source files form the smallest app that boots
// and passes `kata verify`: a `GET /health` route that declares input + output
// (ADR-0003), keeps its schema in a separate `*.schema.ts` (ADR-0005), and uses
// no DI — plus a minimal `package.json` / `tsconfig.json` so `tsx src/main.ts`
// actually runs.
//
// The source files are stored as literal strings (not built from the live API)
// because the generated bytes are the locked contract the tests assert. They are
// template literals whose content uses no backticks, so nothing here is escaped.

/** `src/context.ts` — the typed DI surface (ADR-0004); re-exports createApp / defineRoute. */
export const exampleContextSource = `import { defineContext } from 'kata'

// The typed dependency-injection surface for this app (ADR-0004). It starts
// empty — register singleton(...) / scoped<T>() slots here as the app grows,
// then read them inside handlers with c.get('key').
export const k = defineContext({})

export const { defineRoute, createApp } = k
`

/** `src/main.ts` — entry point: createApp({ modules }) + serve from @hono/node-server. */
export const exampleMainSource = `import { serve } from '@hono/node-server'

import { createApp } from './context'
import * as health from './modules/health/health.route'

const app = createApp({ modules: [health] })

const port = Number(process.env['PORT'] ?? 3000)

serve({ fetch: app.fetch, port }, (info) => {
  console.log('kata: listening on http://localhost:' + info.port)
})
`

/** `src/modules/health/health.route.ts` — GET /health, the smallest valid route. */
export const exampleHealthRouteSource = `import { defineRoute } from '../../context'

import { HealthSchema } from './health.schema'

// Liveness probe: GET /health -> 200 {"status":"ok"}. The smallest valid Kata
// route — it declares input and output (ADR-0003), keeps its schema in
// health.schema.ts (ADR-0005), and uses no DI. Add real modules beside it under
// src/modules/<domain>/.
export const healthRoute = defineRoute({
  method: 'GET',
  path: '/health',
  input: {},
  output: HealthSchema,
  handler: () => ({ status: 'ok' as const }),
})
`

/** `src/modules/health/health.schema.ts` — the HealthSchema Zod DTO (ADR-0005). */
export const exampleHealthSchemaSource = `import { z } from 'zod'

// Response DTO for GET /health (ADR-0005). Schemas live in their own *.schema.ts
// so they can be reused by name and imported by the route.
export const HealthSchema = z.object({
  status: z.literal('ok'),
})

export type Health = z.infer<typeof HealthSchema>
`

/**
 * `package.json` for the generated app. Emitted only-if-absent (ADR-0015) so a
 * re-run inside a project that already has a manifest never clobbers it. Mirrors
 * `examples/hello` so the deps are known-good; `kata` resolves from npm once the
 * user installs (the one manual `pnpm install` step the scaffold can't do).
 */
export const examplePackageJson = {
  name: 'kata-app',
  version: '0.0.0',
  private: true,
  type: 'module',
  scripts: {
    dev: 'tsx watch src/main.ts',
    start: 'tsx src/main.ts',
    test: 'echo "No tests yet"',
    typecheck: 'tsc --noEmit',
  },
  dependencies: {
    '@hono/node-server': '^1.13',
    hono: '^4',
    kata: '^0.1.0',
    zod: '^3',
  },
  devDependencies: {
    '@types/node': '^20',
    tsx: '^4.19',
    typescript: '^5.6',
  },
}

/**
 * `tsconfig.json` for the generated app. Self-contained (it cannot extend the
 * Kata monorepo base) with the options the four source files need: Bundler
 * resolution for the extensionless relative imports, strict + verbatim module
 * syntax to match Kata conventions, and `node` types for `process` / `console`.
 * Emitted only-if-absent like `package.json`.
 */
export const exampleTsconfig = {
  compilerOptions: {
    target: 'ES2022',
    module: 'ESNext',
    moduleResolution: 'Bundler',
    lib: ['ES2022'],
    types: ['node'],
    strict: true,
    noUncheckedIndexedAccess: true,
    esModuleInterop: true,
    verbatimModuleSyntax: true,
    skipLibCheck: true,
    resolveJsonModule: true,
    noEmit: true,
  },
  include: ['src'],
}
