// Templates for the runnable app that `kata init` scaffolds (issue #200).
//
// `kata init [dir]` produces a *complete, runnable* Kata app following the
// mandatory layout in AGENTS.md — `src/app.ts`, `src/context.ts`, a
// `src/middlewares/` folder, and `src/modules/<domain>/` modules each with the
// full `route` / `service` / `schema` / `test` / `hurl` five-file set. Two
// example modules ship so a newcomer sees the canonical GET *and* POST shapes:
//
//   • `health`   — GET /health, the smallest liveness probe.
//   • `greetings` — POST /greetings (validated body) + GET /greetings/:id
//                   (validated params, 404 on miss): the create/read pattern.
//
// This supersedes ADR-0015 D1, which scaffolded only a minimal two-file app
// behind `--with-example`; issue #200 makes the full app the default `kata init`
// output (`--minimal` keeps the old harness-only behaviour). See the new
// bootstrap ADR for the decision record.
//
// ── Template delivery (issue #200, open question) ────────────────────────────
// Templates are **inline strings compiled into `dist/`**, not a `templates/`
// directory shipped in the package. `package.json#files` lists only `dist`, so
// tsup bundles these strings into the CLI bundle and the published tarball stays
// a single `dist` tree — no second copy of the templates to ship, drift from, or
// add to `files`. The trade-off (templates are not browsable as standalone files
// in the tarball) is acceptable: they are plain exported constants here, fully
// readable in source, and the generated bytes are the locked contract asserted
// in `generators.test.ts`.
//
// All generated sources avoid backticks/`${}` (they use string concatenation
// instead), so each template below is a clean backtick literal needing no
// escaping — the same convention the original example templates used.

/** `src/context.ts` — the typed DI surface (ADR-0004); re-exports the bound factory. */
export const exampleContextSource = `import { defineContext } from 'katajs'

// The typed dependency-injection surface for this app (ADR-0004). It starts
// empty — register singleton(...) / scoped<T>() slots here as the app grows,
// then read them inside handlers and middleware with c.get('key').
export const k = defineContext({})

// Re-export the bound factory so every module inherits this app's exact types:
// c.get('key') only compiles for keys registered above.
export const { defineRoute, defineMiddleware, createApp } = k

export type AppRegistry = typeof k.registry
`

/** `src/app.ts` — composes the app: modules + the app-level middleware chain. */
export const exampleAppSource = `import { createApp } from './context'
import { requestLogger } from './middlewares/request-logger'
import * as greetings from './modules/greetings/greetings.route'
import * as health from './modules/health/health.route'

// The application (AGENTS.md layout: app.ts === createApp). Modules are plain
// namespace imports — each file's exported routes are registered in order. The
// app-level middleware chain (ADR-0012) runs before every route; add
// cross-cutting concerns (cors(), secureHeaders(), bodyLimit() from 'kata') here.
export const app = createApp({
  modules: [health, greetings],
  middlewares: [requestLogger],
})
`

/** `src/main.ts` — runtime entry: serve the app from @hono/node-server. */
export const exampleMainSource = `import { serve } from '@hono/node-server'

import { app } from './app'

const port = Number(process.env['PORT'] ?? 3000)

serve({ fetch: app.fetch, port }, (info) => {
  console.log('kata: listening on http://localhost:' + info.port)
})
`

/** `src/middlewares/request-logger.ts` — a no-DI app-level middleware example. */
export const exampleRequestLoggerSource = `import { defineMiddleware } from '../context'

// Example app-level middleware (ADR-0012): runs before every route's own use:
// chain. It logs the method + path of each request and provides no scoped slots.
// Wire app-level middleware in app.ts via createApp({ middlewares: [...] }).
export const requestLogger = defineMiddleware({
  provides: [],
  handler: async (c, next) => {
    const { method, path } = c.raw.req
    console.log('[req] ' + method + ' ' + path)
    await next()
  },
})
`

// ── health module — GET /health (the smallest liveness probe) ────────────────

/** `src/modules/health/health.schema.ts` — the HealthSchema Zod DTO (ADR-0005). */
export const exampleHealthSchemaSource = `import { z } from 'zod'

// Response DTO for GET /health (ADR-0005). Schemas live in their own *.schema.ts
// so they can be reused by name and imported by the route.
export const HealthSchema = z.object({
  status: z.literal('ok'),
})

export type Health = z.infer<typeof HealthSchema>
`

/** `src/modules/health/health.service.ts` — the pure liveness check. */
export const exampleHealthServiceSource = `import type { Health } from './health.schema'

// Services are plain, pure functions (no framework imports) — trivial to unit
// test. The route is the only place that knows about HTTP.
export function checkHealth(): Health {
  return { status: 'ok' }
}
`

/** `src/modules/health/health.route.ts` — GET /health, the smallest valid route. */
export const exampleHealthRouteSource = `import { defineRoute } from '../../context'

import { HealthSchema } from './health.schema'
import { checkHealth } from './health.service'

// Liveness probe: GET /health -> 200 {"status":"ok"}. The smallest valid Kata
// route — it declares input and output (ADR-0003), keeps its schema in
// health.schema.ts (ADR-0005), and uses no DI.
export const healthRoute = defineRoute({
  method: 'GET',
  path: '/health',
  input: {},
  output: HealthSchema,
  handler: () => checkHealth(),
})
`

/** `src/modules/health/health.test.ts` — unit test for the service. */
export const exampleHealthTestSource = `import { describe, expect, it } from 'vitest'

import { checkHealth } from './health.service'

describe('checkHealth', () => {
  it('reports ok', () => {
    expect(checkHealth()).toEqual({ status: 'ok' })
  })
})
`

/** `src/modules/health/health.hurl` — API E2E (literal host; run against a live server). */
export const exampleHealthHurlSource = `# API E2E for the health module. Run with the server already listening:
#   pnpm start    # in another terminal
#   pnpm hurl

GET http://localhost:3000/health
HTTP 200
[Asserts]
jsonpath "$.status" == "ok"
`

// ── greetings module — POST /greetings + GET /greetings/:id (create/read) ────

/** `src/modules/greetings/greetings.schema.ts` — the greetings DTOs (ADR-0005). */
export const exampleGreetingsSchemaSource = `import { z } from 'zod'

// All Zod schemas for a domain live here, never inline in the route (ADR-0005) —
// the route imports them by name. Export the z.infer types alongside so a single
// import pulls both the runtime validator and the compile-time type.
export const CreateGreetingBodySchema = z.object({
  name: z.string().min(1),
})

export const GreetingParamsSchema = z.object({
  id: z.string(),
})

export const GreetingSchema = z.object({
  id: z.string(),
  message: z.string(),
})

export type CreateGreetingBody = z.infer<typeof CreateGreetingBodySchema>
export type Greeting = z.infer<typeof GreetingSchema>
`

/** `src/modules/greetings/greetings.service.ts` — pure logic + in-memory store. */
export const exampleGreetingsServiceSource = `import type { CreateGreetingBody, Greeting } from './greetings.schema'

// A module-local store stands in for a database — swap it for a real one behind
// the same two functions. Register the db handle as a singleton in context.ts
// (ADR-0004) and read it via c.get('db') when you do.
const greetings = new Map<string, Greeting>()

export function createGreeting(input: CreateGreetingBody): Greeting {
  const id = crypto.randomUUID()
  const greeting: Greeting = { id, message: 'Hello, ' + input.name + '!' }
  greetings.set(id, greeting)
  return greeting
}

export function getGreeting(id: string): Greeting | null {
  return greetings.get(id) ?? null
}
`

/** `src/modules/greetings/greetings.route.ts` — POST + GET, body + params + 404. */
export const exampleGreetingsRouteSource = `import { defineRoute } from '../../context'

import { CreateGreetingBodySchema, GreetingParamsSchema, GreetingSchema } from './greetings.schema'
import { createGreeting, getGreeting } from './greetings.service'

// POST /greetings — validates the JSON body against CreateGreetingBodySchema
// (ADR-0003) before the handler runs, then returns the created greeting.
export const createGreetingRoute = defineRoute({
  method: 'POST',
  path: '/greetings',
  input: { body: CreateGreetingBodySchema },
  output: GreetingSchema,
  handler: (c) => createGreeting(c.input.body),
})

// GET /greetings/:id — validates the path param, then reads the greeting back.
// A miss returns the unified ADR-0008 error envelope with a 404.
export const getGreetingRoute = defineRoute({
  method: 'GET',
  path: '/greetings/:id',
  input: { params: GreetingParamsSchema },
  output: GreetingSchema,
  handler: (c) => {
    const greeting = getGreeting(c.input.params.id)
    if (!greeting) return c.error('not_found', 'Greeting not found', { status: 404 })
    return greeting
  },
})
`

/** `src/modules/greetings/greetings.test.ts` — unit tests for the service. */
export const exampleGreetingsTestSource = `import { describe, expect, it } from 'vitest'

import { createGreeting, getGreeting } from './greetings.service'

describe('greetings.service', () => {
  it('creates a greeting with a generated id and a message', () => {
    const greeting = createGreeting({ name: 'Ada' })
    expect(greeting.id.length).toBeGreaterThan(0)
    expect(greeting.message).toBe('Hello, Ada!')
  })

  it('reads a created greeting back by id', () => {
    const created = createGreeting({ name: 'Linus' })
    expect(getGreeting(created.id)).toEqual(created)
  })

  it('returns null for an unknown id', () => {
    expect(getGreeting('does-not-exist')).toBeNull()
  })
})
`

/** `src/modules/greetings/greetings.hurl` — end-to-end POST then GET by captured id. */
export const exampleGreetingsHurlSource = `# API E2E for the greetings module. Run with the server already listening:
#   pnpm start    # in another terminal
#   pnpm hurl

# Create a greeting, capture the returned id, then read it back.
POST http://localhost:3000/greetings
Content-Type: application/json
{ "name": "Ada" }
HTTP 200
[Captures]
greeting_id: jsonpath "$.id"
[Asserts]
jsonpath "$.message" == "Hello, Ada!"

GET http://localhost:3000/greetings/{{greeting_id}}
HTTP 200
[Asserts]
jsonpath "$.message" == "Hello, Ada!"
`

/** `.gitignore` for the generated app — node_modules + common build output. */
export const exampleGitignoreSource = `node_modules
dist
*.log
.DS_Store
lefthook-local.yml
`

/** `README.md` for the generated app — quickstart + the example endpoints. */
export function exampleReadme(name: string): string {
  return `# ${name}

A new [Kata](https://github.com/VicenzoMF/kata) app, scaffolded with \`kata init\`.

## Run it

\`\`\`bash
pnpm install
pnpm dev        # tsx watch src/main.ts -> http://localhost:3000
\`\`\`

## Endpoints

| Method | Path              | Description                          |
|--------|-------------------|--------------------------------------|
| GET    | /health           | Liveness probe -> \`{ "status": "ok" }\` |
| POST   | /greetings        | Create a greeting (body: \`{ "name" }\`) |
| GET    | /greetings/:id    | Read a greeting by id (404 if absent) |

\`\`\`bash
curl localhost:3000/health
curl -X POST localhost:3000/greetings -H 'content-type: application/json' -d '{"name":"Ada"}'
\`\`\`

## Verify your work

- \`pnpm test\`      — unit tests (Vitest).
- \`pnpm typecheck\` — \`tsc --noEmit\`.
- \`kata verify\`    — fast deterministic lint rules (ADR-0003/0004/0005).
- \`pnpm hurl\`      — API E2E (needs [Hurl](https://hurl.dev) installed and the
  server running: \`pnpm start\` in another terminal).

## Add a module

\`\`\`bash
kata new orders   # scaffolds src/modules/orders/ (route/service/schema/test/hurl)
\`\`\`

Then register it in \`src/app.ts\`:

\`\`\`ts
import * as orders from './modules/orders/orders.route'
// ...
createApp({ modules: [health, greetings, orders], middlewares: [requestLogger] })
\`\`\`

## Layout

\`\`\`
src/
├── app.ts                # createApp({ modules, middlewares })
├── context.ts            # defineContext({ ... }) — the typed DI surface
├── main.ts               # serve(app)
├── middlewares/
└── modules/<domain>/     # route / service / schema / test / hurl
\`\`\`

See \`AGENTS.md\` for the conventions every agent (and you) should follow.
`
}

/**
 * `package.json` for the generated app. Emitted only-if-absent (a re-run inside a
 * project that already has a manifest never clobbers it). The name is derived
 * from the target directory. Deps mirror examples/hello so they are known-good;
 * the lint/test/harness toolchain (biome, oxlint, lefthook, vitest) ships so the
 * generated lefthook.yml and the agent harness work after one `pnpm install`.
 */
export function examplePackageJson(name: string): Record<string, unknown> {
  return {
    name,
    version: '0.0.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'tsx watch src/main.ts',
      start: 'tsx src/main.ts',
      test: 'vitest run',
      typecheck: 'tsc --noEmit',
      verify: 'kata verify',
      hurl: 'hurl --test --color src/modules/health/health.hurl src/modules/greetings/greetings.hurl',
      format: 'biome check --write .',
      lint: 'oxlint',
    },
    dependencies: {
      '@hono/node-server': '^1.13',
      hono: '^4',
      // The framework is published to npm as `katajs` (the `kata` name was taken);
      // the CLI/bin is still `kata`, so scripts and hooks call `kata verify`.
      katajs: '^0.1.0',
      zod: '^3',
    },
    devDependencies: {
      '@biomejs/biome': '^2.4.15',
      '@types/node': '^20',
      lefthook: '^2.1.8',
      oxlint: '^1.66.0',
      tsx: '^4.19',
      typescript: '^5.6',
      vitest: '^4.1.7',
    },
  }
}

/**
 * `tsconfig.json` for the generated app. Self-contained (it cannot extend the
 * Kata monorepo base) with the options the source files need: Bundler resolution
 * for the extensionless relative imports, strict + verbatim module syntax to
 * match Kata conventions, and `node` types for `process` / `console` / `crypto`.
 * Emitted only-if-absent like `package.json`.
 *
 * Stored as a raw string (not an object run through `JSON.stringify`) so the
 * bytes match Biome's JSON formatter exactly: Biome collapses short primitive
 * arrays (`"lib": ["ES2022"]`) onto one line, which `JSON.stringify` cannot, and
 * the generated app ships `biome.json`. Kept valid JSON — the tests `JSON.parse`
 * it to assert structure.
 */
export const exampleTsconfigSource = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": ["ES2022"],
    "types": ["node"],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "esModuleInterop": true,
    "verbatimModuleSyntax": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "noEmit": true
  },
  "include": ["src"]
}
`
