#!/usr/bin/env tsx
/**
 * Executable entry for the `kata-docs-mcp` bin. Resolves the bundled
 * `data/docs` next to this file (ADR-0023) — a sibling of `src/` in dev and
 * of `dist/` once built, so the same relative path works whether this runs
 * via `tsx src/main.ts` or as the published `dist/main.js`, regardless of
 * the caller's cwd. `data/docs` is generated by `scripts/copy-docs.mjs`
 * (run by both `start` and `build`), not checked in.
 */
import { fileURLToPath } from 'node:url'

import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'

import { buildIndex } from './indexer'
import { createServer } from './server'

const docsRoot = fileURLToPath(new URL('../data/docs', import.meta.url))

const index = buildIndex(docsRoot)
const server = createServer(index)
const transport = new StdioServerTransport()
await server.connect(transport)
